### ISSUE TITLE
친구 삭제

### ISSUE THREAD

**Issue by Hae-Dal** [ii-news-feed/ii-news-feed-backend#12]
### 작업 설명

친구 목록에 존재하는 유저를 목록에서 삭제합니다.

### 기능 설명

`DELETE` `/api/friends/{fromUserId}/friend/{toUserId}`

##### header

```
{
  Content-Type: application/json
  Authorization: Bearer {token}
}
```

##### pathValuable

```json
{
  "fromUserId" : 1
  "toUserId" : 2
}
```

##### body

```json
{
  "userId" : 1 // 임시, 향후 JWT로 대체
}
```

##### body
- 성공시 : HTTP Status 200
- 실패시 : HTTP Status  404 Not Found

  ```json
  {
        "code" : 404
        "message" :  "존재하지 않는 유저번호 입니다."
  }
  ```

### 테스트 케이스
* 유효한 데이터로 요청을 했을 때, 요청한 유저가 친구 목록에서 올바르게 삭제되는지 테스트

**Comment by loadkrnis** [comment]
{
  "id": 1,
  "fromUserId": 123,
  "toUserId": 456,
  "status": "PENDING"
}
