### ISSUE TITLE
친구 조회

### ISSUE THREAD

**Issue by Hae-Dal** [ii-news-feed/ii-news-feed-backend#13]
### 작업 설명

유저의 친구목록을 조회합니다.

### 기능 설명

`GET` `/api/user/{userId}/friends`

userId : 친구 목록을 조회할 유저번호

##### header

```
{
  Content-Type: application/json
  Authorization: Bearer {token}
}
```

##### pathValuable

```json
{
  "userId" : 1
}
```
##### body

```json
{
  "userId" : 1 // 임시, 향후 JWT로 대체
}
```

##### body

- 성공 시 : HTTP Status 200
  ```json
  {
    "contents": [ 
       { "name": "이름", "email": "abc@a.com" }, 
       { "name": "이름", "email": "abc@a.com" },
       { "name": "이름", "email": "abc@a.com" },
    ]
  } 
  ```
- 실패 시 : HTTP Status 404 Not Found

  ```json
  {
        "code" : 404
        "message" :  "존재하지 않는 유저번호 입니다."
  }
  ```

### 테스트 케이스
* 유효한 정보로 요청했을 때, 요청한 유저의 친구 목록을 성공적으로 반환하는지 테스트
* 존재하지 않는 유저번호로 요청했을 때, 에러가 정상적으로 발생하는지 테스트

**Comment by loadkrnis** [comment]
as-is
/api/user/friends/{userId}

to-be
/api/user/{userId}/friends
