### ISSUE TITLE
회원 탈퇴

### ISSUE THREAD

**Issue by Hae-Dal** [ii-news-feed/ii-news-feed-backend#16]
### 작업 설명

회원을 탈퇴합니다.

### 기능 설명

`DELETE` `/api/users/{userId}`

##### header
```
{
  Content-Type: application/json
  Authorization: Bearer {token}
}
```

##### pathValuable

```json
{
  "userId" : 1
}
```

##### body

```json
{
  "userId" : 1 // 임시, 향후 JWT로 대체
  "password": "password1234"
}
```

##### Body
- 성공 시 : HTTP Status 200
- 실패 시 : HTTP Status 400 Bad Request, 404 Not Found

  ```json
  {
        "code" : 400
        "message" : "비밀번호가 일치하지 않습니다."
  }
  ```

  ```json
  {
        "code" : 404
        "message" : "존재하지 않는 유저번호 입니다."
  }
  ```

### 테스트 케이스

* 유효한 정보로 요청했을 때, 회원 탈퇴가 성공적으로 진행되는지 테스트
* 비밀번호가 일치하지 않을 때 에러가 정상적으로 발생하는지 테스트
* 존재하지 않는 유저번호로 요청했을 때, 에러가 정상적으로 발생하는지 테스트

**Comment by loadkrnis** [comment]
DELETE /api/users/{userId}
requestBody 
```json
{
 "userId": 1, // 삭제 예정 JWT
 "password": "password1234"
}
```

{userId} => 삭제할 유저 PK
"userId" => 로그인한 유저 PK 나중에 JWT
