### ISSUE TITLE
뉴스피드 게시물 등록

### ISSUE THREAD

**Issue by HaSeung2** [ii-news-feed/ii-news-feed-backend#5]
### 
**POST /api/posts**
헤더에 토큰이 없거나 유효하지 않으면 예외 발생.
내용을 입력하지 않을 경우 예외 발생.

### RequestBody
```json
{
   "userID" : 1,
   "content" : "내용"
}
```

### ResponseBody
```json
{
   "id" : "1",
   "content" : "내용",
   "createdAt" : "2024-10-21 13:33:33",
   "updatedAt" : "2024-10-21 13:33:33",
   "writer" : {
          "id" : "1",
          "email" : "example@naver.com",
          "name" : "하승"
    }  
}
```
내용을 입력하지 않았을 경우 예외처리
> ### RequestBody
> ```json
> {
>    "content" : null
> }
> ```
> 
> ### ResponseBody
> ```json
> {
>   "code" :  400,
>   "message" : "내용을 입력해주세요."
> }
> ```

### 테스트 케이스
유효한 정보로 접근했을 때 성공적으로 게시물이 등록 되는 지 테스트
내용이 없는 상태로 요청 보냈을 때 에러가 발생하는지 테스트

**Comment by HaSeung2** [comment]
내용을 입력하지 않았을 경우 예외처리
> ### RequestBody
> ```json
> {
>    "content" : null
> }
> ```
> 
> ### ResponseBody
> ```json
> {
>   "code" :  400,
>   "message" : "내용을 입력해주세요."
> }
> ```

토큰이 없을 경우 예외처리
> ### RequestBody
> ```json
> {
>    "content" : "테스트"
> }
> ```
> 
> ### ResponseBody
> ```json
> {
>   "code" :  403,
>   "message" : "토큰이 없습니다."
> }
> ```

토큰이 유효하지 않을 경우 예외처리
> ### RequestBody
> ```json
> {
>    "content" : "테스트"
> }
> ```
> 
> ### ResponseBody
> ```json
> {
>   "code" :  403,
>   "message" : "토큰이 유효하지 않습니다."
> }
> ```

**Comment by loadkrnis** [comment]
requestBody
```json
{
   "userId": 10,
   "content" : "내용"
}
```
