### ISSUE TITLE
프로필 수정(이름) API

### ISSUE THREAD

**Issue by Hamiwood** [ii-news-feed/ii-news-feed-backend#8]
### 작업 설명
저장된 자신의 이름을 수정합니다.

### 기능 설명

PUT/api/users/name

**request**
requestBody
```json
{
    "name" :  "updateName"
}
```

**response**
성공 시 : HTTP Status 200
```json
{ 
   "id" : 1,
   "email" :  "example@email.com",
    "name" :  "hami",
   "createdAt": "2024-10-21 11:11:23",
   "updatedAt": "2024-10-22 11:11:23"
}
```
실패 시 : HTTP Status 401 Unauthorized
```json
{
      "code" : 401
      "message" :  "재 로그인이 필요합니다"
}
```
**테스트 케이스**
+ 유효한 정보로 접근했을 때 성공적으로 해당 회원의 이름이 수정 되는 지 테스트
+ 유효한 정보로 접근했을 때 성공적으로 해당 회원의 정보가 반환 되는 지 테스트
+ 유효하지 않은 토큰, 또는 토큰이 없는 상태로 접근했을 때 에러가 발생하는 지 테스트

**Comment by loadkrnis** [comment]
```json
{
    "userId": 10,
    "name" :  "updateName"
}
```

**Comment by loadkrnis** [comment]
[PUT] /api/user/name
[PUT] /api/user/email
[PUT] /api/user/gender
(X)

[PUT] /api/users
```json
{ 
  "name": "park",
  "password": "asdf"
```
